# Generated by Django 3.1.3 on 2020-12-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_auto_20201227_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='history',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='themes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
